name:                twinpin
version:             0.3.0
github:              "victorjoh/twinpin"
license:             BSD3
author:              "Victor Johnsson"
maintainer:          "victor.johnsson@gmail.com"
copyright:           "Victor Johnsson"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A minimal twin-stick shooter
category:            game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/victorjoh/twinpin#readme>

dependencies:
- base >= 4.12 && < 5

custom-setup:
  dependencies:
  - base >= 4.12 && < 5
  - Cabal >= 2.4
  - zip-archive
  - http-conduit
  - filepath
  - tar
  - directory

data-files: fonts/Aller/*

library:
  source-dirs: src
  ghc-options:
  - -W
  - -Wname-shadowing
  - -O2
  dependencies:
  - sdl2
  - containers
  - extra
  - TypeCompose
  - relude
  - Rasterific
  - JuicyPixels
  - FontyFruity
  - extra
  - composition

executables:
  twinpin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Wname-shadowing
    - -O2
    dependencies:
    - twinpin
    - sdl2
    - containers
    - JuicyPixels
    - FontyFruity
    - Rasterific
    - vector
    - filepath
    - extra

tests:
  twinpin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Wname-shadowing
    dependencies:
    - twinpin
    - hspec
    - sdl2
    - JuicyPixels
    - Rasterific
    - HUnit
    - call-stack