name:                deploy-twinpin
version:             0.2.0
github:              "victorjoh/twinpin"
license:             BSD3
author:              "Victor Johnsson"
maintainer:          "victor.johnsson@gmail.com"
copyright:           "Victor Johnsson"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/victorjoh/twinpin#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -W
  dependencies:
  - process
  - directory
  - filepath
  - zip-archive
  - tar
  - zlib
  - bytestring
  - MissingH
  - time
  - split